[tool.poetry]
name = "parsenvy"
version = "3.0.0-rc3"
description = "Enviously elegant environment variable parsing"
authors = ["Nik Kantar <nik@nkantar.com>"]
license = "BSD-3-Clause"

[tool.poetry.dependencies]
python = "^3.6"

[tool.poetry.dev-dependencies]
mypy = "^0.812"
black = "^20.8b1"
flake8 = "^3.8.4"
pydocstyle = "^5.1.1"
pytest = "^6.2.2"
pytest-watch = "^4.2.0"
coverage = "^5.4"
pytest-cov = "^2.11.1"
pytest-pythonpath = "^0.7.3"
pdbpp = "^0.10.2"

# docs
# note: please also add to [tool.poetry.extras] as appropriate
sphinx = "^3.5.1"
sphinx-rtd-theme = "^0.5.1"

[tool.poetry.extras]
docs = [
  "sphinx",
  "sphinx-rtd-theme",
]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.pytest]
python_paths = "parsenvy"

[tool.coverage.run]
branch = true
source = ["parsenvy"]

[tool.coverage.report]
show_missing = true
