[tool.poetry]
name = "parsenvy"
version = "2.1.0"
description = "Enviously elegant environment variable parsing"
authors = ["Nik Kantar <nik@nkantar.com>"]
license = "BSD-3-Clause"

[tool.poetry.dependencies]
python = "^3.6"

[tool.poetry.dev-dependencies]
mypy = "^0.812"
black = "^20.8b1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
