name: PyPI publishing

on:
  push:
  create:

jobs:
  pypi_publish:
    name: Publish to PyPI

    runs-on: ubuntu-latest

    strategy:
      fail-fast: true

    if: contains(github.ref, 'refs/tags/')

    steps:

        - name: Checkout repository
          uses: actions/checkout@v2

        - name: Set up Python 3.9
          uses: actions/setup-python@v2
          with:
            python-version: 3.9

        - name: Install dependencies
          run: sh bin/cicd_install.sh

        #########################
        # Test PyPI

        - name: Configure Test Pypi
          run: poetry config repositories.testpypi https://test.pypi.org/legacy/

        - name: Publish to Test PyPI
          env:
            TEST_PYPI_TOKEN: ${{ secrets.PARSENVY_TEST_PYPI }}
          run: poetry publish --build -r testpypi -u __token__ -p "$TEST_PYPI_TOKEN"

        - name: Wait a few seconds to avoid race conditions
          run: sleep 5

        - name: Validate test build
          run: sh bin/cd_validate_build.sh test $(poetry version -s)

        #########################
        # PyPI

        - name: Publish to production PyPI
          env:
            PRODUCTION_PYPI_TOKEN: ${{ secrets.PARSENVY_PRODUCTION_PYPI }}
          run: poetry publish -u __token__ -p "$PRODUCTION_PYPI_TOKEN"

        - name: Wait a few seconds to avoid race conditions
          run: sleep 5
          
        - name: Validate build
          run: sh bin/cd_validate_build.sh production $(potery version -s)
